[finder]
keybind_cancel = 'esc'
keybind_select = 'enter'
preview = true
preview_size = 3

[naming]
template = '{{.Host}}/{{.Owner}}/{{.Repository}}/{{.Branch}}'

[naming.sanitize_chars]
'/' = '-'
':' = '-'

[ui]
icons = true
tilde_home = true

[worktree]
auto_mkdir = true
basedir = '~/worktrees'
