[tools]
deno = "latest"
bun = "latest"
go = "latest"
node = "latest"
pnpm = "latest"
python = "latest"
ruby = "latest"
uv = "latest"

usage = "latest"

"npm:@aku11i/phantom" = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:ccusage" = "latest"
"npm:@github/copilot" = "latest"
